/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.classpracticesweek8;

/**
 *
 * @author Sound Room
 */
public class ClassPractice2 extends javax.swing.JFrame {

    /**
     * Creates new form ClassPractice2
     */
    public ClassPractice2() {
        initComponents();

        //adding buttons to groups
        buttonGroup1.add(RadioButtonFahrenheit);
        buttonGroup1.add(RadioButtonCelsius);
        buttonGroup1.add(RadioButtonKelvin);

        buttonGroup2.add(RadioButtonFahrenheit2);
        buttonGroup2.add(RadioButtonCelsius2);
        buttonGroup2.add(RadioButtonKelvin2);

        //making the result temp uneditable
        TextFieldCompTemp.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LabelConvertFrom = new javax.swing.JLabel();
        RadioButtonFahrenheit = new javax.swing.JRadioButton();
        RadioButtonCelsius = new javax.swing.JRadioButton();
        RadioButtonKelvin = new javax.swing.JRadioButton();
        LabelConvertTo = new javax.swing.JLabel();
        RadioButtonFahrenheit2 = new javax.swing.JRadioButton();
        RadioButtonCelsius2 = new javax.swing.JRadioButton();
        RadioButtonKelvin2 = new javax.swing.JRadioButton();
        LabelEnterNumericTemp = new javax.swing.JLabel();
        TextFieldEnterTemp = new javax.swing.JTextField();
        LabelComparableTemp = new javax.swing.JLabel();
        TextFieldCompTemp = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelConvertFrom.setText("Convert from:");

        RadioButtonFahrenheit.setText("Fahrenheit");

        RadioButtonCelsius.setText("Celsius");

        RadioButtonKelvin.setText("Kelvin");

        LabelConvertTo.setText("Convert to:");

        RadioButtonFahrenheit2.setText("Fahrenheit");

        RadioButtonCelsius2.setText("Celsius");

        RadioButtonKelvin2.setText("Kelvin");

        LabelEnterNumericTemp.setText("Enter Numeric Temperature:");

        TextFieldEnterTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldEnterTempActionPerformed(evt);
            }
        });
        TextFieldEnterTemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldEnterTempKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldEnterTempKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldEnterTempKeyTyped(evt);
            }
        });

        LabelComparableTemp.setText("Comparable Temperature is:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelConvertFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEnterNumericTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelComparableTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelConvertTo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioButtonFahrenheit2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonCelsius2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonKelvin2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextFieldEnterTemp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioButtonFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextFieldCompTemp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelConvertFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonFahrenheit)
                    .addComponent(RadioButtonCelsius)
                    .addComponent(RadioButtonKelvin))
                .addGap(32, 32, 32)
                .addComponent(LabelEnterNumericTemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldEnterTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelConvertTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonFahrenheit2)
                    .addComponent(RadioButtonCelsius2)
                    .addComponent(RadioButtonKelvin2))
                .addGap(18, 18, 18)
                .addComponent(LabelComparableTemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldCompTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldEnterTempKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldEnterTempKeyPressed

    }//GEN-LAST:event_TextFieldEnterTempKeyPressed

    private void TextFieldEnterTempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldEnterTempKeyTyped

    }//GEN-LAST:event_TextFieldEnterTempKeyTyped

    private void TextFieldEnterTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldEnterTempActionPerformed

    }//GEN-LAST:event_TextFieldEnterTempActionPerformed

    private void TextFieldEnterTempKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldEnterTempKeyReleased

        //resetting this just in case
        LabelEnterNumericTemp.setText("Enter Numeric Temperature:");

        //when the key is pressed we check which of the top radio buttons is selected ditto with the bottom and convert the temp
        try {

            //creating an input var for simplicity
            int tempInput = Integer.parseInt(TextFieldEnterTemp.getText());

            //huge if else block here
            if ((RadioButtonFahrenheit.isSelected() && RadioButtonCelsius2.isSelected())) {

                //fahrenheit to celsius
                TextFieldCompTemp.setText(Integer.toString((tempInput - 32) * 5/9));

            } else if ((RadioButtonFahrenheit.isSelected() && RadioButtonKelvin2.isSelected())) {

                //fahrenheit to kelvin
                TextFieldCompTemp.setText(Integer.toString((int)((tempInput - 32) * 5/9 + 273.15)));

            } else if ((RadioButtonCelsius.isSelected() && RadioButtonFahrenheit2.isSelected())) {

                //celsius to fahrenheit
                TextFieldCompTemp.setText(Integer.toString((9/5 * tempInput) + 32));

            } else if ((RadioButtonKelvin.isSelected() && RadioButtonFahrenheit2.isSelected())) {

                //kelvin to fahrenheit
                TextFieldCompTemp.setText(Integer.toString((int)((tempInput - 273.15) * 9/5 + 32)));

            } else if ((RadioButtonKelvin.isSelected() && RadioButtonCelsius2.isSelected())) {

                //kelvin to celsius
                TextFieldCompTemp.setText(Integer.toString((int)(tempInput - 273.15)));

            } else if ((RadioButtonCelsius.isSelected() && RadioButtonKelvin2.isSelected())) {

                //celsius to kelvin
                TextFieldCompTemp.setText(Integer.toString((int)(tempInput + 273.15)));

            } else {

                //if anything else is selected like not the right amount we just set the result equal to the entered number
                TextFieldCompTemp.setText(Integer.toString(tempInput));

            }

        } catch (NumberFormatException e) {

            //if they didn't put in a number yell at them and clear the comp temp
            LabelEnterNumericTemp.setText("Enter NUMERIC Temperature:");
            TextFieldCompTemp.setText("");

        }
    }//GEN-LAST:event_TextFieldEnterTempKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassPractice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassPractice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassPractice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassPractice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassPractice2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelComparableTemp;
    private javax.swing.JLabel LabelConvertFrom;
    private javax.swing.JLabel LabelConvertTo;
    private javax.swing.JLabel LabelEnterNumericTemp;
    private javax.swing.JRadioButton RadioButtonCelsius;
    private javax.swing.JRadioButton RadioButtonCelsius2;
    private javax.swing.JRadioButton RadioButtonFahrenheit;
    private javax.swing.JRadioButton RadioButtonFahrenheit2;
    private javax.swing.JRadioButton RadioButtonKelvin;
    private javax.swing.JRadioButton RadioButtonKelvin2;
    private javax.swing.JTextField TextFieldCompTemp;
    private javax.swing.JTextField TextFieldEnterTemp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
