/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.classpracticesweek8;

/**
 *
 * @author Sound Room
 */
public class ClassPractice3 extends javax.swing.JFrame {

    /**
     * Creates new form ClassPractice3
     */
    public ClassPractice3() {
        initComponents();

        //set the error message to initially be invisible, and set all the results tfs to be uneditable
        LabelError.setVisible(false);
        TextFieldBMI.setEditable(false);
        TextFieldCategory.setEditable(false);
        TextFieldHeartRate.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelName = new javax.swing.JLabel();
        LabelAge = new javax.swing.JLabel();
        LabelWeight = new javax.swing.JLabel();
        LabelHeightFeet = new javax.swing.JLabel();
        LabelHeightInches = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        TextFieldAge = new javax.swing.JTextField();
        TextFieldWeight = new javax.swing.JTextField();
        TextFieldHeightFeet = new javax.swing.JTextField();
        TextFieldHeightInches = new javax.swing.JTextField();
        ButtonDisplay = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        TextFieldBMI = new javax.swing.JTextField();
        TextFieldCategory = new javax.swing.JTextField();
        TextFieldHeartRate = new javax.swing.JTextField();
        LabelBMI = new javax.swing.JLabel();
        LabelCategory = new javax.swing.JLabel();
        LabelHeartRate = new javax.swing.JLabel();
        LabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelName.setText("Name:");

        LabelAge.setText("Age:");

        LabelWeight.setText("Weight (lb):");

        LabelHeightFeet.setText("Height (feet):");

        LabelHeightInches.setText("Height (inches):");

        ButtonDisplay.setText("Display");
        ButtonDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDisplayActionPerformed(evt);
            }
        });

        ButtonClear.setText("Clear");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        TextFieldBMI.setText(" ");

        LabelBMI.setText("BMI:");

        LabelCategory.setText("Category:");

        LabelHeartRate.setText("Max Heart Rate:");

        LabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelError.setText("Error!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelHeightFeet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelHeightInches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(TextFieldAge)
                            .addComponent(TextFieldHeightInches, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldHeightFeet, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBMI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(LabelHeartRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldBMI)
                            .addComponent(TextFieldCategory)
                            .addComponent(TextFieldHeartRate, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(LabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelName))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAge)
                    .addComponent(TextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelWeight)
                    .addComponent(TextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHeightFeet)
                    .addComponent(TextFieldHeightFeet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHeightInches)
                    .addComponent(TextFieldHeightInches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDisplay)
                    .addComponent(ButtonClear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBMI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCategory))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelHeartRate))
                .addGap(18, 18, 18)
                .addComponent(LabelError)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed

        //clear all the text fields when the clear button is pressed
        TextFieldName.setText("");
        TextFieldAge.setText("");
        TextFieldWeight.setText("");
        TextFieldHeightFeet.setText("");
        TextFieldHeightInches.setText("");
        TextFieldBMI.setText("");
        TextFieldCategory.setText("");
        TextFieldHeartRate.setText("");

        //also gotta reset the error thingy
        LabelError.setVisible(false);


    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDisplayActionPerformed

        //gotta reset the error thingy
        LabelError.setVisible(false);

        //try and catch that does the bmi formula and sets it in the right text field areas and if it 
        //encounters an error it makes the error message visible
        try {

            //getting the vars for simplicity
            int feet = Integer.parseInt(TextFieldHeightFeet.getText());
            int inches = Integer.parseInt(TextFieldHeightInches.getText());
            int heightInInches = (feet * 12) + inches;
            float weight = Float.parseFloat(TextFieldWeight.getText());
            int age = Integer.parseInt(TextFieldAge.getText());

            //making the bmi
            float BMI = weight / (heightInInches * heightInInches) * 703;
            String BMIFormattedString = String.format("%.1f", BMI);

            //setting it in the corresponding text field
            TextFieldBMI.setText(BMIFormattedString);

            //setting the category text field to the corresponding category through if elses
            if (BMI < 18.5) {

                TextFieldCategory.setText("Underweight");

            } else if (BMI >= 18.5 && BMI <= 24.9) {

                TextFieldCategory.setText("Normal weight");

            } else if (BMI >= 25 && BMI <= 29.9) {

                TextFieldCategory.setText("Overweight");

            } else if (BMI >= 30) {

                TextFieldCategory.setText("Obese");

            }

            //set the max heart rate text field - looked it up and it's close to 220 minus your age
            int heartRate = 220 - Integer.parseInt(TextFieldAge.getText());
            TextFieldHeartRate.setText(Integer.toString(heartRate));

        } catch (NumberFormatException e) {

            //show the error message and clear the results
            LabelError.setVisible(true);
            TextFieldBMI.setText("");
            TextFieldCategory.setText("");
            TextFieldHeartRate.setText("");

        }


    }//GEN-LAST:event_ButtonDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassPractice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassPractice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassPractice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassPractice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassPractice3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDisplay;
    private javax.swing.JLabel LabelAge;
    private javax.swing.JLabel LabelBMI;
    private javax.swing.JLabel LabelCategory;
    private javax.swing.JLabel LabelError;
    private javax.swing.JLabel LabelHeartRate;
    private javax.swing.JLabel LabelHeightFeet;
    private javax.swing.JLabel LabelHeightInches;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelWeight;
    private javax.swing.JTextField TextFieldAge;
    private javax.swing.JTextField TextFieldBMI;
    private javax.swing.JTextField TextFieldCategory;
    private javax.swing.JTextField TextFieldHeartRate;
    private javax.swing.JTextField TextFieldHeightFeet;
    private javax.swing.JTextField TextFieldHeightInches;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldWeight;
    // End of variables declaration//GEN-END:variables
}
