/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.classpracticesweek8;

/**
 *
 * @author Sound Room
 */
public class ClassPractice1 extends javax.swing.JFrame {

    /**
     * Creates new form ClassPractice1
     */
    public ClassPractice1() {
        initComponents();

        //adding the radio buttons to the button group
        buttonGroup1.add(RadioButtonBalcony);
        buttonGroup1.add(RadioButtonMezzanine);
        buttonGroup1.add(RadioButtonOrchestra);

        //making the error anouncement invisible
        LabelError.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LabelTicketNum = new javax.swing.JLabel();
        TextFieldTicketNum = new javax.swing.JTextField();
        checkboxMatinee = new java.awt.Checkbox();
        LabelPriceEach = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();
        RadioButtonOrchestra = new javax.swing.JRadioButton();
        RadioButtonMezzanine = new javax.swing.JRadioButton();
        RadioButtonBalcony = new javax.swing.JRadioButton();
        ButtonCalculatePrice = new javax.swing.JButton();
        PanelPlaceholderTotal = new javax.swing.JPanel();
        LabelTotalResult = new javax.swing.JLabel();
        PanelPlaceholderPrice = new javax.swing.JPanel();
        LabelPriceEachResult = new javax.swing.JLabel();
        LabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTicketNum.setText("Num Tickets");

        checkboxMatinee.setLabel("Matinee");

        LabelPriceEach.setText("Price Each");

        LabelTotal.setText("Total");

        RadioButtonOrchestra.setText("Orchestra");

        RadioButtonMezzanine.setText("Mezzanine");

        RadioButtonBalcony.setText("Balcony");

        ButtonCalculatePrice.setText("Calc Price");
        ButtonCalculatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalculatePriceActionPerformed(evt);
            }
        });

        PanelPlaceholderTotal.setBackground(new java.awt.Color(255, 255, 255));

        LabelTotalResult.setText(" ");

        javax.swing.GroupLayout PanelPlaceholderTotalLayout = new javax.swing.GroupLayout(PanelPlaceholderTotal);
        PanelPlaceholderTotal.setLayout(PanelPlaceholderTotalLayout);
        PanelPlaceholderTotalLayout.setHorizontalGroup(
            PanelPlaceholderTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlaceholderTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTotalResult, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPlaceholderTotalLayout.setVerticalGroup(
            PanelPlaceholderTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlaceholderTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTotalResult)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PanelPlaceholderPrice.setBackground(new java.awt.Color(255, 255, 255));

        LabelPriceEachResult.setText(" ");

        javax.swing.GroupLayout PanelPlaceholderPriceLayout = new javax.swing.GroupLayout(PanelPlaceholderPrice);
        PanelPlaceholderPrice.setLayout(PanelPlaceholderPriceLayout);
        PanelPlaceholderPriceLayout.setHorizontalGroup(
            PanelPlaceholderPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlaceholderPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPriceEachResult, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPlaceholderPriceLayout.setVerticalGroup(
            PanelPlaceholderPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlaceholderPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPriceEachResult)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        LabelError.setText("Error!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButtonMezzanine, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonOrchestra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonCalculatePrice)
                                .addGap(54, 54, 54)
                                .addComponent(LabelPriceEach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelTicketNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldTicketNum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkboxMatinee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelPlaceholderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelPlaceholderPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelTicketNum)
                        .addComponent(TextFieldTicketNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkboxMatinee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RadioButtonOrchestra)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonMezzanine)
                .addGap(18, 18, 18)
                .addComponent(RadioButtonBalcony)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPriceEach)
                            .addComponent(ButtonCalculatePrice))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTotal)
                            .addComponent(LabelError))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelPlaceholderPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelPlaceholderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCalculatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalculatePriceActionPerformed

        //try and except to catch if the text field is empty when they hit the button
        try {

            //defining integers for the price of a ticket and for the number of tickets
            int ticketPrice = 0;
            int totalPrice = 0;
            int numTickets = Integer.parseInt(TextFieldTicketNum.getText());

            //making this thing so we can keep track of whether or not a radio button is selected
            boolean typeSelected = true;

            LabelError.setVisible(false);

            //for each of the three options, if it's selected we set the price each as the cost and the 
            //total as the cost per * numTickets
            if (RadioButtonOrchestra.isSelected()) {

                ticketPrice = 85;
                totalPrice = numTickets * ticketPrice;

            } else if (RadioButtonMezzanine.isSelected()) {

                ticketPrice = 70;
                totalPrice = numTickets * ticketPrice;

            } else if (RadioButtonBalcony.isSelected()) {

                ticketPrice = 45;
                totalPrice = numTickets * ticketPrice;

            } else {

                //if they didn't pick a ticket option show the error message and clear the each and total places
                LabelError.setVisible(true);
                LabelTotalResult.setText(" ");
                LabelPriceEachResult.setText(" ");

                typeSelected = false;

            }

            //if and only if there's a button selected:
            if (typeSelected) {

                //Sets the price and total labels:
                //setting the price label to the price per ticket
                LabelPriceEachResult.setText("$" + ticketPrice);

                //if the matinee is selected multiply the total cost by 85% bc of the 15% discount
                if (checkboxMatinee.getState()) {

                    totalPrice = (int) (totalPrice * 0.85);

                }

                //then we set the total equal to it
                LabelTotalResult.setText("$" + Integer.toString(totalPrice));

            }

        } catch (NumberFormatException e) {

            //show the error message and clear the each and total places
            LabelError.setVisible(true);
            LabelTotalResult.setText(" ");
            LabelPriceEachResult.setText(" ");

        }


    }//GEN-LAST:event_ButtonCalculatePriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassPractice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassPractice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassPractice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassPractice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassPractice1().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCalculatePrice;
    private javax.swing.JLabel LabelError;
    private javax.swing.JLabel LabelPriceEach;
    private javax.swing.JLabel LabelPriceEachResult;
    private javax.swing.JLabel LabelTicketNum;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JLabel LabelTotalResult;
    private javax.swing.JPanel PanelPlaceholderPrice;
    private javax.swing.JPanel PanelPlaceholderTotal;
    private javax.swing.JRadioButton RadioButtonBalcony;
    private javax.swing.JRadioButton RadioButtonMezzanine;
    private javax.swing.JRadioButton RadioButtonOrchestra;
    private javax.swing.JTextField TextFieldTicketNum;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Checkbox checkboxMatinee;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
